### GET all links

GET http://{{$dotenv SERVERNAME}}:{{$dotenv PROXYPORT}}/api/getall

### GET link by id

GET http://{{$dotenv SERVERNAME}}:{{$dotenv PROXYPORT}}/api/getbyid/3

### edit link using GET method by id and rendering of edit form

GET http://{{$dotenv SERVERNAME}}:{{$dotenv PROXYPORT}}/api/edit/3

### POST new link

POST http://{{$dotenv SERVERNAME}}:{{$dotenv PROXYPORT}}/api/insert
Content-Type: application/json

{
    "linkName": "OpenAI",
    "link": "https://www.openai.com",
    "description": "OpenAI is an artificial intelligence research laboratory consisting of the for-profit OpenAI LP and the non-profit OpenAI Inc."
}

### Using PUT update existing link by id

PUT http://{{$dotenv SERVERNAME}}:{{$dotenv PROXYPORT}}/api/update
Content-Type: application/json

{
    "id": 5,
    "description": "OpenAI is an AI research laboratory."
}

### DELETE link by id

DELETE http://{{$dotenv SERVERNAME}}:{{$dotenv PROXYPORT}}/api/delete/5
